### PR TITLE
[DE/DE-formal] Interaction messages

### PR DESCRIPTION
**Pull request by strarsis**
@DanielBiegler: UI interaction confirmation feature [was added to Pannellum](https://github.com/mpetroff/pannellum/pull/952) which also adds [new interaction message strings](https://github.com/mpetroff/pannellum/blob/5f0a1d8662272cae87ad23d367ab041ca3a2d34a/src/js/pannellum.js#L142-L145).
This PR adds the German non-formal and formal translations for these new strings.

### CODE REVIEW

**Comment by DanielBiegler** [comment]
Nice work on the [PR](https://github.com/mpetroff/pannellum/pull/952)! I'll get this merged now but updating the npm package has to wait a day or two. :)

**Comment by DanielBiegler** [comment]
Oh btw @strarsis would you like to take over this repo and the npm package? Then I can stop being a bottleneck for future updates.

**Comment by strarsis** [comment]
@DanielBiegler: Yes, you can make me repo maintainer, if you'd like.
Edit: And I need the npm credentials so I can push the packages under the same author/name?

**Comment by DanielBiegler** [comment]
@strarsis you need to delete your fork of this repo, else I get the following error: 

> strarsis/pannellum-translation already exists

After that you'll get a confirmation mail. More info from Github: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

Also I need your NPM username, after that I'll sort that out, here the npm docs: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by strarsis** [comment]
@DanielBiegler: This passed out of mind a bit, sorry.

1. The GitHub fork `strarsis/pannellum-translation` was deleted.
2. Please re-start the transfer so I can get the confirmation email and confirm the transfer.
3. My npm username is `strarsis` (same as in GitHub).

**Comment by DanielBiegler** [comment]
@strarsis OK, I started the transfer on Github, check your mail. I added you as a maintainer on NPM as well. Please confirm when you accept. After you confirm I can remove myself! Have a nice day! :)

**Comment by strarsis** [comment]
@DanielBiegler: OK, transfer is completed. I am maintainer now of the `pannellum-translation` package and this repository was transferred to my GitHub account.

**Comment by DanielBiegler** [comment]
Nice. I removed myself from NPM now. Cheers.

**Pull request merged**
