### PR TITLE
Create es-mx.json

### PR DESCRIPTION
**Pull request by Sirivasv**
Spanish from México translation.

### CODE REVIEW

**Comment by DanielBiegler** [comment]
Thank you! 

I assumed that the ISO 639-3 had all the info we need but I cant find mexico. I think we should switch to [these](https://en.wikipedia.org/wiki/ISO_3166-1) then. I'll add this to the review queue.

**Comment by Sirivasv** [comment]
Cool, It's kind of special that one but I have seen how some sites add it's own specific translation.
Thanks for considering it!

**Comment by DanielBiegler** [comment]
Yeah languages are a **huge** topic. I've done some research now and decided on a system that should work indefinitely. Check the README in master for more info.

**Review by DanielBiegler — CHANGES_REQUESTED** [review]
due to the new language code standard, this file should be named "MX" instead of "es-mx"

**Comment by Sirivasv** [comment]
Renamed

**Review by DanielBiegler — APPROVED** [review]

**Comment by DanielBiegler** [comment]
Thanks!

**Pull request merged**
