### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by dignissimus**

### CODE REVIEW

**Review by louiswolfers — CHANGES_REQUESTED** [review]
Obvious errors, like "es compatible con imagens" in line 10 (it should be "es compatible con imágenes"), and some sentences don't make sense.

**Comment by louiswolfers** [comment]
I don't want to be that guy, but it still has many errors (even the file name is incorrect). I translated it correctly (#27)

**Comment by DanielBiegler** [comment]
Thank you guys. There are new changes to the file names. Due to the possibility of dialects and such(which the old spec did not really support). Check the new README in master for infos.

**Comment by DanielBiegler** [comment]
I went with #27. Thank you anyway for your time.

**Pull request closed without merging**
