### PR TITLE
Add swedish translation

### PR DESCRIPTION
**Pull request by ulrikstrid**
Solves #11

### CODE REVIEW

**Review by DanielBiegler — CHANGES_REQUESTED** [review]
due to the new language codes the filename has to be changed to "SE". check the README in master if youre curious.

**Comment by ulrikstrid** [comment]
Will fix during the day

**Comment by ulrikstrid** [comment]
I have now changed to name of the file. Amended my commit to keep the history clean.

**Review by DanielBiegler — APPROVED** [review]

**Comment by DanielBiegler** [comment]
Still looking for someone to review this. This will most likely get merged sooner or later. 👍

**Comment by DanielBiegler** [comment]
Thanks!

**Pull request merged**
