### PR TITLE
Add brazilian portuguese translation

### PR DESCRIPTION
**Pull request by jhisse**
Add brazilian portuguese translation

### CODE REVIEW

**Comment by DanielBiegler** [comment]
Very cool, thank you. I'm adding this to the review-queue. After I can get someone to verify this, it'll get merged.

**Comment by strarsis** [comment]
@mozgbrasil, @jessescn, @KitsuneModder, @pasqualot: You seem to be brazilian portuguese native speakers.
Could you have a quick check of [these translations](https://github.com/strarsis/pannellum-translation/pull/14/files), so that I can merge them?

**Comment by Covre912** [comment]
Hey, how do you have my @?

**Comment by strarsis** [comment]
@KitsuneModder: I searched for GitHub repositories for Brazilian-Portuguese translations.

**Comment by strarsis** [comment]
@jhisse: Thank you for this translation.
Pardon my ignorance/pretentiousness but I found two things where something could be changed?
1. Is it intentional that in string `Clique para\nCarregar\nPanorama` the verb `Carregar` and the noun `Panorama` start with a capital letter? Those words are on a separate line each, is this the reason why they start with a capital letter?
2. `por %s` - does this mean "for" or "from" author `%s`, shouldn't this be "de"?

**Comment by strarsis** [comment]
@jhisse: I really want to merge this. Could you take a look at this?

**Comment by jhisse** [comment]
Hi @strarsis , sorry for the delay in my reply. I will look at this soon.

**Comment by strarsis** [comment]
@jhisse: Awesome! In the next phase some new fields are added for the next Pannellum release (UX interaction confirmation).

**Comment by jhisse** [comment]
@strarsis the original fork of this PR was deleted. Please, close this PR and consider [this](https://github.com/strarsis/pannellum-translation/pull/46).

**Pull request closed without merging**
